### ISSUE TITLE
API Key public on Github

### ISSUE THREAD

**Issue by pelensky** [backslashbaker/weather_manager#2]
Sorry Derek, I should have mentioned this when we were chatting. 

API keys should be in environment variables. There's a few ways of doing it, I've used [this package](https://www.npmjs.com/package/dotenv) before! 

Probably worth hiding this API key behind an environment variable. 

[Here's](https://help.github.com/articles/removing-sensitive-data-from-a-repository/) some info on how to remove the API key from Github

**Comment by backslashbaker** [comment]
All sorted
